Dockerfile
dirtviz.py

Created docker image for serving a bokeh website with static data as a tmp monitoring solution for the fuel cells

Create docker image

---

.github/workflows/test.yml
dirtviz/db/conn.py
dirtviz/db/get_or_create.py
dirtviz/db/getters.py
dirtviz/db/tables.py
dirtviz/db/utils/import_rl_csv.py
dirtviz/db/utils/import_teros_csv.py
dirtviz/integrations/http.py
dirtviz/main.py
import_example_data.py
pylintrc

21 enable code linting

---

docker-compose-prod-api.yml
docker-compose-prod-cs_http.yml

Closes #25 
Renamed http-integration to cs-http-integration and the api service to http-api

Updated service names

---

docker-compose-api.yml
docker-compose-cs_http.yml
docker-compose.yml

Closes #22 
Added back in missing docker compose files for production services

22 missing docker compose httpyml

---

docker-compose-prod-api.yml

Added port 8090 to HTTP api

---

dirtviz/integrations/cs_http.py
docker-compose-cs_http.yml
docker-compose-prod-cs_http.yml

Update cs_http from 8090 to 8100

---

dirtviz/integrations/decoder.py

Added lambda function for conv from str to int for ts

---

dirtviz/integrations/decoder.py

Removed int type from type list

---

dirtviz/integrations/api.py

The same cell name was being passed to add_data(), had to update one of the indices

Updated incorrect function args in api.py

---

sql/backup.sh
sql/restore.sh

Added backup and restore scripts

---

README.md

Added deployment information to README

---

dirtviz/db/conn.py

Migrated SQLAlchemy to 2.x

---

backend/api/__init__.py
backend/api/database/models/cell.py
backend/api/database/models/logger.py
backend/api/database/models/power_data.py
backend/api/database/models/teros_data.py
backend/api/database/schemas/cell_data_schema.py
backend/api/database/schemas/p_input.py
backend/api/database/schemas/t_input.py
backend/api/database/schemas/teros_data_schema.py
backend/api/resources/power_data.py
backend/api/resources/teros_data.py

- add post req for teros, power data tables for new json template
json template:
```
{
"type": "teros12",
"cell": "testcell2",
"ts": 1685155868296292287,
"vwc": 200,
"raw_vwc": 2000,
"temp": 200,
"ec": 10
}
{
"type": "rocketlogger",
"logger": "testlogger",
"cell": "testcell2",
"ts": 1685155767595461805,
"v": 100,
"i": 20
}
```

Adding post req for teros power

---

backend/api/database/models/power_data.py
backend/api/database/models/teros_data.py
backend/api/database/schemas/get_cell_data_schema.py
backend/api/resources/power_data.py
backend/api/resources/teros_data.py
backend/requirements.txt
frontend/src/components/DateRangeSel.jsx
frontend/src/pages/dashboard/Dashboard.jsx
frontend/src/services/power.js
frontend/src/services/teros.js
requirements.txt

- connected datetime components to backend sql range query

added date range query for charts

---

frontend/src/pages/dashboard/Dashboard.jsx

changes:
- only calls API on selected state 
- stopped calling call API on selected state uninitialized

Refactor chart render

---

frontend/src/pages/dashboard/Dashboard.jsx

when date is selected, charts are updated

add chart updates when date is selected

---

frontend/src/charts/Chart.jsx
frontend/src/charts/PwrChart/PwrChart.jsx
frontend/src/charts/TempChart/TempChart.jsx
frontend/src/charts/VChart/VChart.jsx
frontend/src/charts/VwcChart/VwcChart.jsx
frontend/src/pages/dashboard/Dashboard.jsx

fixed state of zoom and pan not toggling with change of chart dates

Fix zoom bug

---

frontend/src/charts/ChartWrapper.jsx
frontend/src/charts/PwrChart/PwrChart.jsx
frontend/src/charts/TempChart/TempChart.jsx
frontend/src/charts/VChart/VChart.jsx
frontend/src/charts/VwcChart/VwcChart.jsx
frontend/src/charts/plugins.js
frontend/src/pages/dashboard/Dashboard.jsx

- updated btn state of charts to be independent.
- TODO: optimize state handling, especially during loading states.

fixed pan and zoom btns state

---

.github/workflows/deploy.yml

- updated github deploy yaml with aws credentials

updated for s3 bucket deployment

---

.github/workflows/deploy.yml

- removed usage of docker file for build

Updated frontend build steps

---

.github/workflows/deploy.yml
.github/workflows/destroy.yml
.github/workflows/dev.yml
docker-compose.yml

- setup dev environment trigger on pull request
- updated destroy to trigger on pull request close and destroys environment also

Refactor pipeline

---

frontend/.eslintrc.json
frontend/src/pages/dashboard/Dashboard.jsx
frontend/src/pages/dashboard/components/DateRangeSel.jsx
frontend/src/setupTests.js

Fix frontend build

---

frontend/src/charts/PwrChart/PwrChart.jsx
frontend/src/charts/TempChart/TempChart.jsx
frontend/src/charts/VChart/VChart.jsx
frontend/src/charts/VwcChart/VwcChart.jsx
frontend/src/pages/dashboard/components/PowerCharts.jsx
frontend/src/pages/dashboard/components/TerosCharts.jsx

- fixed extra left column showing up before load

removed extra column before load

---

.github/workflows/destroy.yml
.github/workflows/dev.yml
.github/workflows/setup.yml
.github/workflows/test.yml
.vscode/settings.json

- added create deployment when pull req is opened
- added python formatter

updated workflow and added black formatter

---

backend/api/resources/health_check.py
frontend/src/pages/home/About.jsx

changed hero text in about page

---

frontend/src/pages/dashboard/Dashboard.jsx

- moved leaf chart down to not crowd charts

moved leaf chart down

---

frontend/src/charts/VwcChart/VwcChart.jsx

- changed max for vwc axis to 0.65 and ec axis to 650
- needed to change both to have the steps match in the chart

changed max for vwc axis to 0.65 and ec axis to 650

---

backend/api/__init__.py
frontend/vite.config.js

fix-aws-routing

---

.github/workflows/test.yml

runs vitest during the test workflow

added vitest to test workflow

---

frontend/vite.config.js

added esbuild rule to ignore console.logs

removed console log on build

---

frontend/src/pages/dashboard/components/PowerCharts.jsx
frontend/src/pages/dashboard/components/TerosCharts.jsx

chart now update on date change

added chart update on date change

---

frontend/src/pages/dashboard/components/PowerCharts.jsx
frontend/src/pages/dashboard/components/TerosCharts.jsx

stream now queries for 30 seconds later than local time

increase stream query offset

---

.github/workflows/deploy.yml

Test: changed to deployment for quick fix

---

.github/workflows/test.yml
backend/api/database/models/power_data.py
backend/api/database/models/teros_data.py

adding black formatter to workflow

adding black formatter to workflow

---

frontend/src/components/Nav.jsx
frontend/src/services/auth.js

small ui changes and logout now redirects to landing

updated logout redirect and added menu to profile

---

backend/api/database/models/teros_data.py
backend/api/resources/power_data.py
backend/api/resources/teros_data.py
frontend/src/assets/downsample.svg
frontend/src/charts/ChartWrapper.jsx
frontend/src/charts/PwrChart/PwrChart.jsx
frontend/src/charts/TempChart/TempChart.jsx
frontend/src/charts/VChart/VChart.jsx
frontend/src/charts/VwcChart/VwcChart.jsx
frontend/src/pages/dashboard/components/DateRangeSel.jsx
frontend/src/pages/dashboard/components/PowerCharts.jsx
frontend/src/pages/dashboard/components/TerosCharts.jsx
frontend/src/services/power.js

adding downsampling toggle button to charts

feat: downsample charts

---

frontend/src/charts/PwrChart/PwrChart.jsx
frontend/src/charts/SensorChartTemplate.jsx
frontend/src/charts/TempChart/TempChart.jsx
frontend/src/charts/VChart/VChart.jsx
frontend/src/charts/VwcChart/VwcChart.jsx
frontend/src/charts/alignAxis.js

added service that aligns ticks for charts with no defined max. It aligns the ticks based off of the maximum datapoint in the dataset and calculates a new max that is a defined number of steps away and using a step count based off of a defined factor.

211 aligning ticks on charts for multiple y axis

---

backend/api/database/models/sensor.py
backend/api/database/schemas/get_sensor_data_schema.py
backend/api/resources/sensor_data.py
frontend/src/pages/dashboard/Dashboard.jsx
frontend/src/pages/dashboard/components/SensorChart.jsx
frontend/src/services/sensor.js

added sensor streaming functionality to sensor models

Add sensor stream

---

.github/workflows/deploy.yml
.github/workflows/deploy_dev.yml

migrated main to push to development environment

updated dev frontend deployment

---

.github/workflows/deploy_dev.yml
.github/workflows/test.yml

dev branch now deploys to dev environment in aws

updated development environment workflow

---

.github/workflows/deploy.yml

main branch deploys to prod on change

update prod workflow

---

backend/api/resources/cell_data.py
frontend/src/pages/dashboard/components/DownloadBtn.jsx
frontend/src/services/cell.js

removed react query & added streaming

refactored csv endpoint to prevent sigkill

---

frontend/src/charts/alignAxis.js

All tick steps are now set as positive numbers

fixed negative steps in alignAxis breaking chart template

---

frontend/src/pages/dashboard/components/DownloadBtn.jsx

added exponential backoff to download status checks

adding exp backoff to download status checks

---

.github/workflows/deploy.yml

Update deploy.yml naming

---

backend/entrypoint.sh

Changed the log levels of production celery worker to reduce memory footprint on big queries

updated prod log level of celery worker to warning

---

backend/api/auth/auth.py
backend/gunicorn.conf.py
backend/wsgi.py

fixed login error with monkey patching

hotfix: monkey patch before gunicorn and remove depreciated datetime

---

.github/workflows/test.yml
codecov.yml
frontend/vite.config.js

added code cov to test yml

---

backend/api/auth/auth.py
backend/api/database/models/user.py

bugfix: duplicate tokens

---

backend/api/models/cell.py

new cell was not creating due to missing values in cell constructor

added default vals for cell obj

---

README.md
backend/README.md
backend/api/models/logger.py
backend/api/models/power_data.py
backend/api/models/sensor.py
backend/api/resources/cell.py
backend/api/schemas/add_cell_schema.py
backend/tests/conftest.py
backend/tests/test_cell.py
backend/tests/test_health_check.py
backend/tests/test_json_encoder.py
backend/tests/test_power_data.py
backend/tests/test_sensor.py
backend/tests/test_teros_data.py

- added additional power and teros tests
- added sensors tests
- added health check resource functionality test
- migrated db session code to be oop

Adding backend tests

---

backend/api/models/power_data.py
backend/api/models/teros_data.py
backend/api/resources/cell_data.py
backend/tests/conftest.py
backend/tests/test_power_data.py
backend/tests/test_teros_data.py

optimize:
- chart queries, power and teros
- csv parsing

Query optimization

---

frontend/src/pages/map/Map.jsx

I've updated the location of Jlab.

Updated WRP location on the map

---

frontend/src/components/Nav.jsx

Added functionality to make the logo clickable, navigating users to the home page when clicked.
- Wrapped DvIcon component in a Box with onClick handler to navigate to "/"
- Added pointer cursor to provide visual indication of clickability
- Added aria-label for improved accessibility
This enhances user experience by following standard web convention of clickable logos returning to the home page.
- Manually verified logo click navigates to home page
- Confirmed cursor changes to pointer when hovering over logo
- Checked that accessibility tools can recognize the navigation function
https://jam.dev/c/e4e2385a-61d1-4f0a-b5a1-0145fe262481

Functionality to make the logo clickable

---

frontend/src/pages/profile/Profile.jsx
frontend/src/pages/profile/components/CellsList.jsx

Made changes to CellsList.jsx and Profile.jsx

Fix profile page background not expanding properly

---

frontend/src/charts/VChart/VChart.jsx

removed min chart option to not cut off data points at value = 0

removed min from v chart

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/components/Footer.jsx
frontend/src/pages/contact/Contact.jsx

Reverts jlab-sensing/ENTS-backend#420

Revert "Revert "Branch with Contact Us Page""

---

frontend/src/pages/home/About.jsx

I reworded the "Checkout Live Data" button to "View Data" and changed the destination of "Demo" to cell # 413.
Finishes issue #431.

Fixed demo button/home button

---

backend/api/models/sensor.py
frontend/src/pages/dashboard/Dashboard.jsx
frontend/src/pages/profile/components/AddCellModal.jsx
frontend/src/pages/profile/components/DeleteCellModal.jsx
frontend/src/services/cell.js

Fixes multiple UI/UX issues and functionality bugs in the cell management modals to improve user experience and maintain consistency.
- **Fixed coordinate field order**: Latitude now appears before Longitude following geographic standard [lat, long]
- **Fixed broken "Done" button**: Modal now properly closes and resets form after successful cell creation/deletion
- **Fixed form state management**: Removed broken unused state and implemented proper cleanup
- **Professional success messages**: Replaced raw HTML with Material-UI components, added success icons
- **Consistent styling**: Both Add and Delete modals now share the same improved design pattern
- **Better spacing and typography**: Improved readability with proper margins and font styling
- **Copyable API endpoints**: URLs are now …

Improve cell management modals UI/UX and fix functionality bugs

---

backend/api/__init__.py
backend/api/resources/data_availability.py
backend/api/resources/sensor_data_json.py
backend/tests/test_data_availability.py
frontend/src/components/DateRangeNotification.jsx
frontend/src/hooks/useSmartDateRange.js
frontend/src/pages/dashboard/Dashboard.jsx
frontend/src/pages/dashboard/components/SensorChart.jsx
frontend/src/pages/dashboard/components/SoilPotChart.jsx
frontend/src/pages/dashboard/components/TerosCharts.jsx
frontend/src/pages/home/About.jsx
frontend/src/services/dataAvailability.js

Implements a smart date range feature that automatically selects the most recent 2-week period with available data, improving user experience by eliminating empty charts and providing intelligent date selection.
- **New API endpoint**: `/api/data-availability/` that queries across all data tables (Sensor+Data, TEROSData, PowerData) to find latest and earliest timestamps
- **Data availability service**: Returns latest_timestamp, earliest_timestamp, has_recent_data, and user-friendly messages
- **Endpoint registration**: Added to backend API routing
- **Data availability service**: `dataAvailability.js` to call the new API endpoint
- **Smart date range hook**: `useSmartDateRange.js` with intelligent date calculation logic
- Prefers most recent 14-day period if data exists within last 30 …

Add smart date range with automatic fallback to available data periods

---

backend/api/models/cell.py
frontend/src/pages/home/About.jsx

Fixed recurring errors in database relating to unfinished tags model

Fixing tags errors

---

backend/api/resources/util.py
frontend/src/pages/dashboard/components/SoilHumChart.jsx
frontend/src/pages/dashboard/components/WaterFlowChart.jsx
frontend/src/pages/dashboard/components/WaterPresChart.jsx

Added updated measurement fields and corrections to charts related to demo site sensors.

Measurement Corrections to Water Flow and Pressure Charts
